name: Build and deploy docs
on: [push]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-docs:
    environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
    name: Build and deploy MATLAB docs
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1

      - name: Make docs
        uses: matlab-actions/run-command@v1
        with:
          command: make_docs

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './helpfiles'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
