name: Run MATLAB tests
on: [push]

jobs:
  matlab-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1

      - name: Run script
        uses: matlab-actions/run-command@v1
        with:
          command: run_tests
